import { notFound } from "next/navigation";
import type { Metadata } from "next";
import Report from "@/components/Report";
import { getReportBySlug, supabaseConfigured } from "@/lib/supabase";

type PageProps = {
  params: Promise<{ slug: string }>;
};

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  if (!supabaseConfigured()) return { title: "ConnexT" };
  try {
    const row = await getReportBySlug(slug);
    if (!row) return { title: "Report not found · ConnexT" };
    const title = row.name
      ? `${row.name}'s ConnexT report`
      : "A ConnexT report";
    return {
      title,
      description: `A personality + career portrait. Holland Code ${row.scores.riasecCode}.`,
      openGraph: {
        title,
        description: "A personality + career portrait generated by ConnexT.",
      },
    };
  } catch {
    return { title: "ConnexT" };
  }
}

export default async function PublicReportPage({ params }: PageProps) {
  const { slug } = await params;

  if (!supabaseConfigured()) {
    notFound();
  }

  const row = await getReportBySlug(slug);
  if (!row) notFound();

  return (
    <main className="relative z-10 min-h-screen text-[#f5f5f7] flex flex-col">
      {/* Masthead */}
      <div className="max-w-4xl w-full mx-auto px-6 pt-10">
        <div className="flex items-center justify-between">
          <a
            href="/ConnexT"
            className="flex items-center gap-3 group focus-ring rounded-lg"
            aria-label="ConnexT home"
          >
            <Monogram />
            <span className="font-[family-name:var(--font-display)] text-[22px] tracking-tight leading-none group-hover:text-white transition-colors">
              ConnexT
            </span>
          </a>
          <div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.22em] text-white/35">
            <span className="h-1 w-1 rounded-full bg-emerald-400 shadow-[0_0_6px_rgba(52,211,153,0.9)]" />
            by AI Esquire
          </div>
        </div>
        <div className="hairline h-px w-full mt-5" />
      </div>

      {/* Report */}
      <div className="flex-1 flex items-start justify-center px-6 py-16">
        <div className="w-full max-w-3xl">
          <Report
            report={row.report}
            scores={row.scores}
            careers={row.careers}
            slug={row.slug}
            readOnly
          />

          <div className="fade-up text-center pt-12">
            <a
              href="/ConnexT"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-full border border-white/10 text-[11px] uppercase tracking-[0.22em] text-white/50 hover:text-white hover:border-violet-400/40 hover:bg-violet-500/10 transition focus-ring"
            >
              Take the assessment yourself
              <svg
                className="w-3 h-3"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M5 12h14M13 5l7 7-7 7" />
              </svg>
            </a>
          </div>
        </div>
      </div>

      <footer className="relative z-10 py-10 text-center">
        <div className="max-w-3xl mx-auto px-6">
          <div className="hairline h-px w-full mb-6" />
          <p className="text-[10px] uppercase tracking-[0.22em] text-white/30">
            ConnexT · An AI Esquire production
          </p>
        </div>
      </footer>
    </main>
  );
}

function Monogram() {
  return (
    <div className="relative h-10 w-10 rounded-xl overflow-hidden ring-1 ring-white/10">
      <div className="absolute inset-0 bg-gradient-to-br from-violet-500 via-fuchsia-500 to-violet-600" />
      <div className="absolute inset-0 bg-gradient-to-t from-black/40 to-transparent" />
      <span className="absolute inset-0 grid place-items-center font-[family-name:var(--font-display)] text-xl text-white leading-none italic">
        C
      </span>
      <div className="absolute -inset-2 bg-violet-500/30 blur-xl -z-10" />
    </div>
  );
}
